### ISSUE TITLE
support websockets in the RestService/Store abstraction so we can update entities in real time

### ISSUE THREAD

**Issue by jstrachan** [redhat-ipaas/ipaas-ui#114]
we're used in the fabric8 console to having everything using websockets so that we can see quickly when things change without having to poll.

e.g. of 2 folks are working in the same namespace; a Java dev may install some Connectors which then should appear immediately in the Citizen's UI etc.

It'd be nice to at least conceptually support this feature.

I wonder if the use of Observable<Array<T>> is the right abstraction in our underlying models? i.e. if one Foo updates, does that mean we'd have a new Array<T> event and so force a redraw an entire table?

**Comment by jimmidyson** [comment]
If we get an update for a single entity via websockets, then we would replace entity in store array & emit event with full array. We should probably use track by to ensure only changed elements are redrawn rather than whole list.

**Comment by chirino** [comment]
This is done.. events can be obtained via SSE or Websockets.
