### ISSUE TITLE
Sprint 7 Demo

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#119]
What are we expecting to demo, goals, etc. strictly in terms of the UI and from the perspective of the user. We need to prioritize issues in the scope of the demo.

Off the top of my head, our possible goals:

1. oAuth (https://github.com/redhat-ipaas/ipaas-ui/pull/122) & login
2. Aesthetic improvements across entire UI to better reflect designs
3. DataMapper UI? Do we even have an issue open for this?
4. Full template creation user flow?
5. Partial integration user flow? Obviously a full user flow is not possible for this.
6. Additional Connections stuff (#55, #92, #96)? Would this be possible for this demo?
7. Dashboard improvements (empty vs non-empty state, demonstrate both)? This would not be possible without user roles, which is a question I've had for a while.
8. Minor: Modals for all components that require them (#125)
9. Minor: Sortable filter w/ multiple properties "" (#89)
10. Minor: Toast notifications "" (#88)
11. Infinite scrolling & pagination (#46)? Would really like this one

Expected Date: Monday, January 30, 2017

**Comment by gashcrumb** [comment]
I think we kinda came to the conclusion that there wasn't going to be much to demo UI-wise.  Though I could probably show the example code I have in datamapper-ui showing up in ipaas-ui if you like.

**Comment by kahboom** [comment]
@gashcrumb - oh.. should have probably read your comment before updating the issue description with a huge list of likely unreachable goals 😂 lol

**Comment by gashcrumb** [comment]
lol

Yeah, really our goals and what is demoed need to be in line with what we have defined in the sprint, anything on top of that is gravy.

**Comment by kahboom** [comment]
Closing, as this won't be a UI-focused demo.
