### ISSUE TITLE
Connections User Flow Broken

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#126]
Connections user flow broken after refactoring; erhm, need to fix this ASAP.

**Comment by jimmidyson** [comment]
This was known at the time of migrating to the new UI structure.

**Comment by kahboom** [comment]
Personally, I knew it broke parts of the application, but did not realize we wouldn't be able to create connections as a result (my fault obviously), which breaks the connections user flow. Not a big deal; just want to have an issue to reference when I fix it.

**Comment by kahboom** [comment]
Closing this for more specific issues next sprint.
