### ISSUE TITLE
Improve Configurability per Environment

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#130]
It would be very useful to be able to switch, for example, API and auth URLs from a configuration file without worrying about having to switch it back when you are done testing or coding. This file shouldn't get checked in. There would be an example configuration file that users would rename to `config.json`. It adds an extra step in the setup but provides added convenience.

See my proposed solution here and let me know what you think: https://gist.github.com/kahboom/7d1ab66fa0c85bbf20594c9b1cc477cd

Benefits:
- Improved configurability. It would help us reference constant values that can easily be changed from a top level without being hardcoded into the `app.component.ts` file or anywhere else. Values can also be overridden based on the environment while defaulting to `development`.
- DRYer code. We won't be repeating ourselves if we keep all constant values that are browser-side in a single place. The configuration service would still be very helpful as that is where we could write the default to `development` functionality.
- Better unit tests. It also makes it a million times easier to write unit tests and make sure the tests are actually working as expected (failing when they need to, not just passing), as you can easily switch out the title, for instance, and see if it makes the test fail as it should.
- Better E2E testing. This could also be very useful for E2E testing, where you often want to test both remote and local setups (if the dev decides to run E2E tests manually at any given point they should be able to, not only via CI).

Is it overkill refactoring or unnecessary? Possibly. I think the tradeoffs are worth it, but I would love to hear any thoughts.

**Comment by jimmidyson** [comment]
Can't we use cli [environments](https://github.com/angular/angular-cli#build-targets-and-environment-files) for this?

**Comment by kahboom** [comment]
@jimmidyson - Instead of a string for the `env` key? Yes, that'd be a good option, but specifying the environment isn't the main focus here, it's using configuration settings (via JSON objects) that are specific to them, which would require not checking in the `config.json` file. What do you think?
