### ISSUE TITLE
ng-bootstrap only works with bootstrap 4

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-ui#136]
So just started using the tabs from ng-bootstrap and they don't look like tabs really.  Should we move to bootstrap 4?  Wonder, how awful is that going to work with patternfly?

**Comment by gashcrumb** [comment]
Or should we use a bootstrap 3.x compatible set of angular 2 directives is the other question...  Or I guess the next option is just add the necessary CSS to make the ng-bootstrap components look as they should.

**Comment by jimmidyson** [comment]
Can't we just use patternfly markup? Really want to avoid having to play with CSS as much as we can & hoping that patternfly styles are enough...

**Comment by gashcrumb** [comment]
In this case I want to use this kind of markup:

```
<ngb-tabset>
        <ngb-tab title="from scratch">
          <template ngbTabContent>
             Content here..
          </template>
        </ngb-tab>
        <ngb-tab title="from template">
          <template ngbTabContent>
            Moar content
          </template>
        </ngb-tab>
</ngb-tabset>
```

which is from `ng-bootstrap`.  Or we can look into moving to patternfly 4.x and use their refactored components.  Maybe that'd be the best way to go, I guess they've an example.

**Comment by gashcrumb** [comment]
Lemme just have a poke at using patternfly 4.x beta with their components, we'd gain a lot if we could use those given most designs generally make use of those.

**Comment by gashcrumb** [comment]
Hmm, actually `angular-patternfly` itself doesn't provide tabs anyways.  What we need to do is replace `ng-bootstrap` with a dependency that uses bootstrap 3, as `ng-bootstrap` requires bootstrap 4.

Following this [quickstart](https://github.com/patternfly/patternfly-angular2-demo-app) for using `angular-patternfly`, so far so good, I haven't seemed to have broken the ipaas app.  Yet.

**Comment by gashcrumb** [comment]
Nope, `UpgradeAdapter` eventually bombs out with a massive stack trace that hangs the developer console, so that's out I think.  Will look at finding a replacement for `ng-bootstrap`.

**Comment by gashcrumb** [comment]
Trying [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap), also am updating our patternfly dep as well anyways.

**Comment by kahboom** [comment]
Can this be closed out already?

**Comment by gashcrumb** [comment]
oh yes, this is all set, sorry!

**Comment by kahboom** [comment]
No worries! Thanks :)
