### ISSUE TITLE
Broken Unit Tests

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#141]
Several unit tests broken over the past few weeks.

**Comment by jimmidyson** [comment]
`ng test` works for me locally? Plus we have those tests running in PR status checks and haven't noticed any issues?

**Comment by kahboom** [comment]
No idea why, for templates + integrations they were failing for me locally and I fixed them. I was wondering if it could be due to my changes, but my changes did not touch those directories. Now I have tests failing for what I did change, still have one not passing and am working on that before creating a PR.

**Comment by kahboom** [comment]
Closing as this was resolved but due to the parent-child setup that we will no longer be using.
