### ISSUE TITLE
Lint Not Included in CircleCI Checks

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#147]
Running `yarn lint` locally fails for me. I resolved the issues and it is now passing, but the CI builds were still given the green light for all PRs created when checks passed (e.g. unit tests), despite failed linting. This kind of defeats the purpose of linting, so it would be nice to get this working (I thought it was at one point?).

**Comment by jimmidyson** [comment]
I fixed this in 817d8eb1933ee02f2277ed99b672cdab316fbbe6 (evidenced by https://circleci.com/gh/redhat-ipaas/ipaas-ui/228 failure).
