### ISSUE TITLE
Use cucumber for e2e tests

### ISSUE THREAD

**Issue by jludvice** [redhat-ipaas/ipaas-ui#190]
Consider https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2
**EDIT** this is just template project.

**Comment by jludvice** [comment]
Adding following npm dev dependencies
```json
  "devDependencies": {
    "@types/cucumber": "^0.0.37",
    "cucumber": "^1.3.1",
    "cucumber-tsflow": "^1.1.2",
    "protractor-cucumber-framework": "^0.6.0",
  }
```

`protractor-cucumber-framework` configuration - `protractor.conf.js`

```js
  specs: [
    // specs are feature files
    './features/**/*.feature'
  ],
 // switch jasmine to custom (cucumber is not supported framework) 
 framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  cucumberOpts: {
    require: [
       // load steps definitions
      'features/**/*.steps.ts'
    ],
    format: 'pretty'
  },
```

**Comment by jludvice** [comment]
Add `chai` and `chai-as-promised` for assert/expectations on promise objects
https://github.com/domenic/chai-as-promised

**Comment by jludvice** [comment]
Added https://www.npmjs.com/package/cucumber-html-reporter to generate html report.

I needed to create `env.js` file where are some cucumber configurations, like 
* global timeout
* taking screenshot in `After` step

working example of `env.js` (note it must be included in `protractor.conf.js`)
```js
module.exports = function () {

  this.setDefaultTimeout(400 * 1000);

  /**
   * create screenshot after each cucumber scenario
   */
  this.After(function (scenario, next) {
    browser.takeScreenshot().then(function (png) {
      var decodedImage = new Buffer(png, 'base64');
      scenario.attach(decodedImage, 'image/png', next);
    }, function (err) {
      next(err);
    });
  });

};
```

Lot of [comments](https://github.com/cucumber/cucumber-js/issues/275) suggest this snipped for attaching screenshots, 
but it didn't work for me because data was encoded incorrectly - needed to remove `.toString('binary');` 
```js
      browser.takeScreenshot().then(function (png) {
        var fs = require('fs');

        //var base64Image = new Buffer(png, 'binary').toString('base64');
        var decodedImage = new Buffer(png, 'base64').toString('binary');

        scenario.attach(decodedImage, 'image/png');
      });
```

**Comment by kahboom** [comment]
Completed w/ https://github.com/redhat-ipaas/ipaas-ui/pull/308
