### ISSUE TITLE
Create Integration: Add Step

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#206]
## Overview
Add the ability to add another step when creating an Integration in the UI. Entails the following:
- Add HTML & SCSS to reflect designs & incorporate logic.
- Add method(s) called by HTML for saving/publishing, essentially creating, the Integration in its respective component (confirmation here needed), or optionally adding another step.

### Relevant Designs

![add step](https://cloud.githubusercontent.com/assets/3844502/23571568/06d8c256-0038-11e7-9c26-15cca98b4f4a.png)

## Reference
- [GitHub: Create Integration](https://github.com/redhat-ipaas/ipaas-ui/issues/76)
- [GitHub: Create Integration: Save or Add Step](https://github.com/redhat-ipaas/ipaas-ui/issues/205)
- [Design: Create Integration: Add Step](https://redhat.invisionapp.com/share/RJAPPPEGN)
- [JIRA: UI](https://issues.jboss.org/browse/IPAAS-231)

**Comment by gashcrumb** [comment]
This is done
