### ISSUE TITLE
Create Integration - Connection ring color change

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-ipaas/ipaas-ui#248]
Once a user is done with setting up connection, the ring around the connection icon should be blue, not gray. Should remain blue for rest of flow.

<img width="333" alt="screen shot 2017-03-13 at 12 17 36 pm" src="https://cloud.githubusercontent.com/assets/16257540/23871479/d4d0fdac-07e7-11e7-8afe-e4655a56e966.png">

**Comment by gashcrumb** [comment]
Apparently this isn't showing up correctly still
