### ISSUE TITLE
Create Integration - Sub step states

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-ipaas/ipaas-ui#250]
Once sub steps for a connection/step are complete, they should no longer appear disabled when the connection is expanded. Text color should be black as opposed to the light gray they are now.

<img width="346" alt="screen shot 2017-03-13 at 12 20 23 pm" src="https://cloud.githubusercontent.com/assets/16257540/23872319/0f4b1348-07eb-11e7-9b2d-6661c7e31456.png">

**Comment by gashcrumb** [comment]
Fixed this in my last PR that also sorted the top-level step highlighting.
