### ISSUE TITLE
Update Integration List

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-ipaas/ipaas-ui#253]
Update design to make integrations easier to click to edit.

Also changed label design so they don't look like buttons.

<img width="1042" alt="screen shot 2017-03-13 at 12 53 39 pm" src="https://cloud.githubusercontent.com/assets/16257540/23872617/33cae436-07ec-11e7-8493-ef72846b34b6.png">

## Reference
- [JIRA: Add Start/Finish Icons](https://issues.jboss.org/browse/IPAAS-313)

**Comment by dongniwang** [comment]
@catrobson you made a comment during last week's demo about why we put the EDIT in the kebab (instead of having it visible within the rows), can you please share your insight here as well? Thank you!

**Comment by kahboom** [comment]
Not sure what changes need to be made here or if I implemented them already and just forgot, but here is a screenshot of what I have for the Integration List:

![](https://www.dropbox.com/s/wlmvlyg6ucwlafw/Screenshot%202017-03-21%2011.09.05.png?dl=0)

**Comment by kahboom** [comment]
At the moment, the mouse changes when you hover over the Active label, were we still allowing users to activate/deactivate integrations from there? Or just from the kebab dropdown? Also, what are we doing about editing?

**Comment by sjcox-rh** [comment]
@kahboom @dongniwang @gashcrumb Here are the details for updating the integration List discussed during our meeting today:

Updates to Integration List page to be made:

-Toggle switch for active/inactive states
-Click on Integration to be able to Edit
-In progress state for integration getting deployed
-Global Notification for when integration is deployed and user is on a different page.
-Add in integration status icon from dashboard

**Comment by kahboom** [comment]
Perfect @sjcox-rh , thank you!

**Comment by kahboom** [comment]
Updated designs:

![integration list](https://cloud.githubusercontent.com/assets/3844502/24523368/d4e20a08-1560-11e7-9b14-490f46a96169.jpg)

![integration list 02](https://cloud.githubusercontent.com/assets/3844502/24523371/d779558c-1560-11e7-96c4-14d7497226d1.jpg)

Empty:

![integration empty](https://cloud.githubusercontent.com/assets/3844502/24523380/db48a6cc-1560-11e7-842b-54d5690f138c.png)

Filter:

![integration filter](https://cloud.githubusercontent.com/assets/3844502/24523383/dd5fcf8a-1560-11e7-88af-72bed2a93593.png)
