### ISSUE TITLE
Run `lint` as part of running tests in dev mode?

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-ui#257]
So my IDE does most of the lint work but sometimes I miss the squiggles.  Running `yarn run lint` takes forever and it doesn't watch for changes.  Would it make sense to have the `test` script maybe run the lint task before executing the tests?

**Comment by kahboom** [comment]
I had spoken with Jimmi about this before as it was something I was
interested in, but I know he expressed not wanting to add anything that
would slow the development process while we are pressed for time, including
a longer build cycle. Not sure if that's still the case?

Regards,

*Rachel Yordán*
Senior Software Engineer
Red Hat, Inc. | Middleware
ryordan@redhat.com

**Comment by gashcrumb** [comment]
Yeah, I wouldn't want to have it run as part of `yarn run start` for example, as I want recompilation/refreshing to happen quickly.  But I usually also have `yarn run test` running in another terminal and check that typically before committing changes to see what I broke, was thinking it could be nice if the linting was also done in this step.

That being said I could probably stop being lazy and just remember to do `yarn run lint` before pushing :-)

**Comment by gashcrumb** [comment]
nah

**Comment by kahboom** [comment]
rofl
