### ISSUE TITLE
Integrate the DataMapper

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#263]
## Overview
Add the ability to add a data mapping in the UI. Entails the following:
- Add HTML & SCSS to reflect designs & incorporate logic.
- Add method(s) called by HTML for creating a data mapping.
- Add logic to communicate with internal data store and SSE/Websocket for bi-directional model synchronization (and to initiate notifications)?? N/A?

### Relevant Designs
N/A

## Reference
- [JIRA Issue: UI](https://issues.jboss.org/browse/IPAAS-263)
- [JIRA Issue: User Story](https://issues.jboss.org/browse/IPAAS-240)

**Comment by kahboom** [comment]
@gashcrumb - Would you consider this to be complete?

**Comment by gashcrumb** [comment]
So, it's in there, haven't been able to fully validate that it's working though.
