### ISSUE TITLE
Create Integration: Add Filter Step

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#266]
## Overview
Add the ability to filter data as a step when creating an integration in the UI. Entails the following:
- Add HTML & SCSS to reflect designs & incorporate logic.
- Add method(s) called by HTML for adding the filter step and making the call to the REST API in its respective component.

### Relevant Designs
N/A

![]()

## Reference
- [InVision: Design]()
- [JIRA Issue: UI](https://issues.jboss.org/browse/IPAAS-270)
- [JIRA User Story](https://issues.jboss.org/browse/IPAAS-245)

**Comment by gashcrumb** [comment]
Step is in place.
