### ISSUE TITLE
Integration Editor - Inconsistent state on refresh

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-ui#269]
When I'm on a page in the integration editor and I refresh, the state of the editor is inconsistent, there appears to be a race to track down between the page loading, the components initializing and the integration getting loaded from the server.

**Comment by gashcrumb** [comment]
Think this commit should sort this issue -> https://github.com/redhat-ipaas/ipaas-ui/pull/292/commits/dbf4061fc8d7f0032ddd02cfd71af48a92b4420d

**Comment by gashcrumb** [comment]
I think this is all set with that commit

**Comment by kahboom** [comment]
Thanks @gashcrumb
