### ISSUE TITLE
Integration Editor - Line needs some work in the empty state case

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-ui#272]
Also when there's just the two connections and the '+' the line isn't continuous.  For example:

![screencapture-localhost-4200-integrations-edit-4-connection-select-1-1489678667742](https://cloud.githubusercontent.com/assets/351660/24004603/1e8eca3a-0a3d-11e7-8a27-3bdc89934bf0.png)

**Comment by gashcrumb** [comment]
@kahboom are you working on this?  Wonder if maybe we just need to take out the `min-height` for the flow view container, that'd sort this out pretty quickly...

**Comment by kahboom** [comment]
@gashcrumb Well I was, but it's okay, that might actually be the best solution.

**Comment by kahboom** [comment]
@gashcrumb - I think you fixed this with your last commit, but can you please confirm that this is no longer an issue when you add multiple steps or are in an empty state? If it's fixed, please close the issue so I can move it to 'Release Candidate/Completed'. Thanks! :)

**Comment by gashcrumb** [comment]
Yeah, I think this is working better, we can leave folks to raise issues if it isn't :-)
