### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by kcbabo** [redhat-ipaas/ipaas-ui#296]
## Overview
Need to update the dashboard page so that it shows the summary view when we have at least one integration deployed. Entails the following:
- Add HTML & SCSS to reflect designs & incorporate logic.
- Add method(s) called by HTML for counting filtered integrations to display accurate data.
- Add method(s) called by HTML to request filtered integrations and connections from the API.

cc @KurtStam @chirino - We need to be provided with properties that include the last date/time an integration was updated and the messages exchanged (count, it will be displayed to the user as "No. of times Used" - see design below for reference). Honestly, the API should accept query params like `/api/v1/integrations?sort=lastUpdated&asc=true&limit=10` if it doesn't already. We could do the sorting and filtering from the UI but it will get messy quickly. It's also probably best practice to do this from the API. The "count" for active, inactive, and draft integrations required by the designs is not a big deal and can be done from the UI if anything.

## Designs

**Dashboard**

![225246638](https://cloud.githubusercontent.com/assets/3844502/24380465/75f44586-1319-11e7-8218-cf98e34fe0ee.png)

![225246460](https://cloud.githubusercontent.com/assets/3844502/24380462/73716294-1319-11e7-95fc-d39eee1862b5.png)

## Reference
- [GitHub: Dashboard: Empty State](https://github.com/redhat-ipaas/ipaas-ui/issues/300)
- [GitHub: API Issue](https://github.com/redhat-ipaas/ipaas-rest/issues/246)
- [InVision Design: Dashboard 01](https://redhat.invisionapp.com/share/VQ8UZ7PCE#/225246638_IPaaS_Dashboard_3-23_P1-1x)
- [InVision Design: Dashboard 02](https://redhat.invisionapp.com/share/VQ8UZ7PCE#/225246460_IPaaS_Dashboard_3-23_P2-1x)
- [JIRA Issue: UI](https://issues.jboss.org/browse/IPAAS-280)
- [JIRA User Story](https://issues.jboss.org/browse/IPAAS-279)

**Comment by kahboom** [comment]
Note: After discussing with @sjcox-rh and @dongniwang, the design will remain the same with the exception of the templates being replaced with Connections. The checkmark icons on the left-hand side represent that status of the integration, which is not currently implemented. For demoing purposes they will be left there (and incorporated into the Integration List view), but will not have any functional purpose until preview.

**Comment by gashcrumb** [comment]
@KurtStam @chirino we'll need field on integrations that tracks how many exchanges have been processed to support this view.  For the 'recent changes' area seems like we'd need a rest API to fetch the most recent git commits, or better still an API that summarizes changes to a user's integrations based on the git commits?  git commits would probably be too low level?

**Comment by kahboom** [comment]
Needs minor tweaks, but done.
