### ISSUE TITLE
Change behavior for integration name/description

### ISSUE THREAD

**Issue by kcbabo** [redhat-ipaas/ipaas-ui#297]
Do not require integration name and description to be defined up front.  Generate default integration name based on start/finish connections.  If user wants to change name or add description, they can click on the name field in the upper left.

Make description optional.

**Comment by gashcrumb** [comment]
Put in a PR yesterday that removed the name requirement until the user clicks 'save'.

Will need to work on auto-generating the name.  @KurtStam we might need a field on an Integration that we can use to store if the name is auto-generated or set by the user.

**Comment by gashcrumb** [comment]
Oh and also made the description optional.

**Comment by gashcrumb** [comment]
@sjcox-rh @dongniwang if we auto-generate the name, should we more aggressively truncate the description in the integration list view?  It may be with an auto-generated name the user could never actually set a description.

**Comment by gashcrumb** [comment]
Will open a separate issue for auto-generating the name, we now just require the name if it's not set when you click 'save'.
