### ISSUE TITLE
Completed connections and steps should not have 'active' color

### ISSUE THREAD

**Issue by kcbabo** [redhat-ipaas/ipaas-ui#298]
When I complete a step or connection in the integration editor, the text still shows with an 'active' (bright blue) color.  The text should be grey when I'm not actively configuring a step/connection.

**Comment by gashcrumb** [comment]
This should be sorted with my latest PR, looks like it's updated on staging if you want to take a peek.

**Comment by gashcrumb** [comment]
This is all set.
