### ISSUE TITLE
Back, next, cancel with connections

### ISSUE THREAD

**Issue by kcbabo** [redhat-ipaas/ipaas-ui#310]
I'm starting to question the utility of Next, Back, and Cancel when configuring connections in the integration editor.  IMO, we should change these so that:

- They only appear the first time you configure a connection (when you have three steps).
- They should be local to a connection.  For example, if you're in the Finish connection, you can't "Back" into a prior step or the start connection.
- They should not appear when clicking on a connection after it's been configured.  In this case, you click on the connection to configure it.  There's only one thing to do.  If you want to do something else, you just click away.

**Comment by kahboom** [comment]
Bringing in @sjcox-rh @dongniwang and @gashcrumb for the discussion.

**Comment by kahboom** [comment]
Ah @gashcrumb beat me to it lol 👍

**Comment by kahboom** [comment]
@gashcrumb - Is this resolved for now (to be closed?) or should I put it in the backlog?

**Comment by gashcrumb** [comment]
Let's close it
