### ISSUE TITLE
bump typescript-logging version to last stable

### ISSUE THREAD

**Issue by jludvice** [redhat-ipaas/ipaas-ui#317]
Bump version to allow usage of typescript logging in e2e tests.
Issue issue https://github.com/mreuvers/typescript-logging/issues/3 is fixed in 0.2.1.
from `"typescript-logging": "0.2.0-beta6",`
to `"typescript-logging": "^0.2.1",`

**Comment by kahboom** [comment]
Completed with https://github.com/redhat-ipaas/ipaas-ui/pull/308
