### ISSUE TITLE
Create Integration: plus(+) buttons disappers when middle step is deleted

### ISSUE THREAD

**Issue by dsimansk** [redhat-ipaas/ipaas-ui#319]
When middle step is removed during editing (with "trash bin" icon), "plus buttons" are no longer displayed.

<img width="1176" alt="screen shot 2017-03-27 at 15 24 56" src="https://cloud.githubusercontent.com/assets/5637792/24358889/e47ff0b6-1302-11e7-8f44-61c827890ac9.png">

<img width="1102" alt="screen shot 2017-03-27 at 15 24 05" src="https://cloud.githubusercontent.com/assets/5637792/24358910/f07a7c74-1302-11e7-8db6-e6237e4845ea.png">

**Comment by gashcrumb** [comment]
Looks like after deleting the step the we're on the wrong page, i.e. we shouldn't be on the 'choose a connection' page at all here.
