### ISSUE TITLE
Add Collapsibility to Vertical Navigation

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#32]
## Overview

For some reason, the collapsible feature on the hamburger icon isn't working properly. Probably just missing some JS. :)

**Comment by gashcrumb** [comment]
This works now, doesn't it?  Or do we need an e2e test for it still?

**Comment by kahboom** [comment]
I was just waiting to write an e2e test for it, but of course haven't gotten around to that.

**Comment by gashcrumb** [comment]
No worries, it's blocked on #52 anyways
