### ISSUE TITLE
Create integration fails silently

### ISSUE THREAD

**Issue by jludvice** [redhat-ipaas/ipaas-ui#328]
After creating integration in ipaas-ui and clicking on publish,
I'm redirected on Integration list page, but my integration is **not present** and **I didn't see any error message**.

Inspecting Chrome -> Network tab, I can see HTTP 400 - **bad request** with response
to url https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/api/v1/integrations
with response
```
Unrecognized field &quot;statusType&quot; (class com.redhat.ipaas.model.integration.Integration$Builder), not marked as ignorable
```

![screenshot_20170328_140135](https://cloud.githubusercontent.com/assets/8707241/24403877/289968d8-13bf-11e7-9455-bc3cf434e495.png)

**Comment by jludvice** [comment]
CC @gashcrumb @kahboom @dsimansk

**Comment by gashcrumb** [comment]
Yep, probably need to update the model looks like.  You'll also notice there's a TODO in the code on error handling at the moment :-)

**Comment by jludvice** [comment]
Status update - now i see some error master on commit 28e8950fb2a93468cb99aa7b323ab50ba3b2b970
![integration-error](https://cloud.githubusercontent.com/assets/8707241/24445870/d1cf9e84-146b-11e7-9ba9-5fa8641512f0.png)

**Comment by gashcrumb** [comment]
Yup, that's it *not* failing silently :-)  But we get a timeout error from the backend which we can't do much about in the frontend, so I think this particular issue is all set from the UI perspective.

@sjcox-rh Do we have an 'error saving' design?  I stuck in this quick alert as a stopgap so we at least don't lose the user's work on the frontend side...

**Comment by KurtStam** [comment]
@gashcrumb @jludvice Can list any server exception that reaches the UI here? I can't really see what exception is thrown above exactly since it is a screenshot. We are attempting to handle them all, but it looks like some are slipping through. So if you list them I can go after them. Note that this won't fix the gateway timing out exception. That needs to be address in the whatever the gateway is on OpenShift OnLine.

**Comment by gashcrumb** [comment]
So that's from the gateway timeout, I think we've some code client-side that's seeing that null response and throwing that error possibly.

**Comment by kahboom** [comment]
Was this resolved?

**Comment by gashcrumb** [comment]
As far as the UI is concerned, yes...

**Comment by kahboom** [comment]
Okay, closing this for now then.
