### ISSUE TITLE
Create Integration - Hide popup menu in connection list

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-ui#345]
Like this shouldn't show up.  Also selecting a connection feels wonky, like the click handler doesn't take effect necessarily.

![screencapture-localhost-4200-integrations-create-connection-select-0-1490818133673](https://cloud.githubusercontent.com/assets/351660/24474268/1547390a-149a-11e7-86a4-9bc7886cd6c6.png)

**Comment by kahboom** [comment]
Sorry @gashcrumb the click handler is my fault (actually both problems are), as I removed the `(click)` attribute. I'll re-add them in. The first part is a result of re-using templates, but we can work around that. I don't think it's a showstopper for the demo though.

**Comment by gashcrumb** [comment]
Ah yeah that `(click)` handler is super important :-)

It should have also been involved in the connection list page as well.  If we change the dropdown menu to also trigger via a `(click)` handler then we shouldn't run into issues with nesting click handlers.  It's only a problem now because those dropdowns are being triggered via patternfly jquery code.
