### ISSUE TITLE
Connection List: boxed-area clickable size might be too small

### ISSUE THREAD

**Issue by dsimansk** [redhat-ipaas/ipaas-ui#347]
Connections listed in boxes are pretty hard to select when not clicked to `Title` or area around it. User might expect that whole boxed-area is clickable. Same applies for selecting connector in create connection page.

Could we rearrange the div a bit better to enlarge registered area for click to benefit from relatively large boxed-area.

![screen shot 2017-03-30 at 11 08 17](https://cloud.githubusercontent.com/assets/5637792/24496723/57af9f04-1539-11e7-8cc9-edaf4090f395.png)

**Comment by kahboom** [comment]
I just finished doing this, as the kabob menu was creating a conflict. After this sprint I'd like to add an event blocker  so that the whole card can become clickable again except if it's the kabob. If I get a chance I'll squeeze it in, or add padding for now so that area (with the name) is larger and has more surface area to click on and make the description & icon clickable as well.

**Comment by kahboom** [comment]
Was just discussing this with @gashcrumb yesterday (regarding #345). Might work on the `event.preventDefault()` today in that case.

**Comment by jludvice** [comment]
What do you think about this @kahboom isn't this too "hackish"?
https://github.com/jludvice/ipaas-ui/commit/c4a2265b6137d8022d42722741b0c16d19dc0251

**Comment by gashcrumb** [comment]
Use a (click) handler instead and you shouldn't have to deal with
event.preventDefault()...

**Comment by kahboom** [comment]
@jludvice - Personally, yes. I think @gashcrumb 's solution is probably the best for now.. I'll re-add the click handlers in about an hour. Got really sick yesterday evening and couldn't work.

**Comment by gashcrumb** [comment]
@kahboom actually here, ng2-bootstrap would probably be the way to go to sort out the click handling -> http://valor-software.com/ng2-bootstrap/#/dropdowns#single-button

**Comment by kahboom** [comment]
@gashcrumb - Right, next sprint. 👍   Ty!

**Comment by kahboom** [comment]
For now I'll use your click handler solution, as you've been doing as well.
