### ISSUE TITLE
Move connection name/description step to end

### ISSUE THREAD

**Issue by kcbabo** [redhat-ipaas/ipaas-ui#365]
When creating a new connection, I don't want to name it or provide a description until after I've selected the connector and provided configuration values.  Let's just move the name/description inputs to step 3.

**Comment by gashcrumb** [comment]
So:

Page 1 => Select connector
Page 2 => Configure Connector
Page 3 => Name Connection and save...

**Comment by kcbabo** [comment]
Works for me.

**Comment by kahboom** [comment]
@gashcrumb - Can this be closed?

**Comment by gashcrumb** [comment]
Durn it, yup it can!  :-)
