### ISSUE TITLE
Working data mapper component

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-ui#376]
Data mapper component is integrated, but doesn't yet work.  Needs to fetch a pom for the current integration the user is working on so that it can supply it to the data mapper backend.

**Comment by chirino** [comment]
Rest API now has the following endpoint: /api/v1/integration-support/generate/pom.xml
POST to it an the current integration.  The integration does not need to exist yet.

**Comment by gashcrumb** [comment]
@chirino I now have the data mapper sending along that pom.xml file with the linked PR.  The mapper component is getting back this response when it goes to use it:

```
{
  "MavenClasspathResponse": {
    "jsonType": "com.mediadriver.atlas.java.v2.MavenClasspathResponse",
    "classpath": "Command returned non-zero exit code: 1",
    "executionTime": 3009
  }
}
```

not really sure what that could mean :-)  Anyways, once the PR is merged it'll be available in staging, I've also created an integration with a mapper step, aptly titled `Test With Mapping`.

**Comment by kahboom** [comment]
Merged your PR @gashcrumb .

**Comment by chirino** [comment]
I think I know what that means.. It can't find mvn.  I'll see if I can fix the docker image.

**Comment by gashcrumb** [comment]
Almost there, hit this on staging -> https://github.com/redhat-ipaas/datamapper-ui/issues/23

**Comment by gashcrumb** [comment]
This PR will also affect this issue -> https://github.com/redhat-ipaas/ipaas-rest/pull/276

**Comment by gashcrumb** [comment]
Also hitting this now -> https://github.com/redhat-ipaas/datamapper-ui/issues/24

**Comment by gashcrumb** [comment]
It works so I think this issue is all set at least.
