### ISSUE TITLE
Adjust UI Contrast for Presentations

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#393]
The gray background PatternFly normally uses gets washed out in presentations and projections and appears white. This needs to be adjusted in time for the Keynote for Red Hat Summit.

cc @sjcox-rh @dongniwang 

[JIRA Issue](https://issues.jboss.org/browse/IPAAS-299)

**Comment by kahboom** [comment]
Per @sjcox-rh:

> The shade we recommend the background be changed to is `#E1E1E1`. This isn't a shade on PatternFly since the lighter shades still weren't visible on Bluejeans so I choose a hex value in between two PatternFly shades.

**Comment by dongniwang** [comment]
Wanted to captured a few other UI contrast related issues here as well. Screenshots were taken from Keith Demo Video on 4/10. 
- Dashboard: The grey color used for Inactive label in the Integration Board section got washed out. (Screenshot 1)
- Create an Integration Workflow: The grey color used for the left visualization pane was not visible enough. 
cc: @sjcox-rh @kahboom @gashcrumb 
![ipaas_dashboard_inactive label](https://cloud.githubusercontent.com/assets/24943812/24917972/c735a8e2-1eac-11e7-9058-000ff83dfbe6.png)
![ipaas_integration_choose a connection](https://cloud.githubusercontent.com/assets/24943812/24918878/ea3b72d8-1eaf-11e7-8536-bd0b0cddc0ba.png)

**Comment by kahboom** [comment]
Thanks @dongniwang - Is it okay for me to use the same gray as the background color we decided on? `#E1E1E1`

**Comment by dongniwang** [comment]
@kahboom - Yes, I think that should work! Thank you!

**Comment by sjcox-rh** [comment]
I love that we're all on the same page! I was thinking the same thing @kahboom and @dongniwang

**Comment by kahboom** [comment]
Done, just need to update the sidebar. See #412.
