### ISSUE TITLE
Create Integration - Save vs Publish Buttons

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-ipaas/ipaas-ui#405]
@kahboom, @gashcrumb, @dongniwang 

Dongni and I were chatting today and noticed button confusion when you go to save your integration. We realize that was because we never updated the workflow mocks when we decided to move the name integration page to the end. Sorry about that!

I've attached two mocks to provide button direction. The first mock shows that when the user is at a point where they can save an integration, there should be a cancel and save button present (save will be primary). If they click save they will be taken to the name integration page. On this page (second mock) the buttons present will be cancel, save as draft, and publish (publish is primary). If the user hits publish it will deploy integration and they will be taken to integration list page. 

Let me know if you have any questions!

![save or add step](https://cloud.githubusercontent.com/assets/16257540/24877828/945332cc-1de5-11e7-9906-83f623a2e949.png)
![name integration](https://cloud.githubusercontent.com/assets/16257540/24877830/948bd1c2-1de5-11e7-97bc-1490e65e3334.png)

**Comment by gashcrumb** [comment]
@sjcox-rh yep, that sounds much better I think, does that make sense @kcbabo?

**Comment by kcbabo** [comment]
Perfect!  We were just discussing this in the keynote demo meeting. :-)

**Comment by gashcrumb** [comment]
Also commented out those dangerous back buttons for now so there's less chance of hitting the wrong button and having disaster strike :-)

**Comment by kcbabo** [comment]
So I

**Comment by kcbabo** [comment]
So I figured out what the most dangerous thing is about the back button - it's that when you back up to the first step, the back button disappears and the cancel button slides right to replace it.  So if you click the back button 3 times quickly and you only have two steps back, that third click is on cancel.

**Comment by gashcrumb** [comment]
Well, that's now not an issue :-)
