### ISSUE TITLE
Connections: Create a Connection

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#41]
## Overview

Write the logic and UI for the Create a Connection component.
## Reference
- [JIRA User Story](https://issues.jboss.org/browse/IPAAS-184)
- [Connections: Connection Library](https://github.com/hawtio/hawtio-ipaas/issues/42)
### InVision Designs:
- [Create a Connection: Step 1](https://redhat.invisionapp.com/share/TJ8KKMWGX#/screens/188000725)
- [Create a Connection: Step 2](https://redhat.invisionapp.com/share/TJ8KKMWGX#/screens/188000724)
- [Create a Connection: Step 2 (Empty State)](https://redhat.invisionapp.com/share/TJ8KKMWGX#/screens/190605969)
- [Create a Connection: Step 2 (Validation)](https://redhat.invisionapp.com/share/TJ8KKMWGX#/screens/190683583)
- [Create a Connection: Step 3](https://redhat.invisionapp.com/share/TJ8KKMWGX#/screens/188000723)

**Comment by kahboom** [comment]
This has been completed as an Angular module. It consists of a template that renders data loaded from an external service (the iPaaS API) through its primary component. Aesthetic improvements and other features require a separate GitHub issue.

**Comment by gashcrumb** [comment]
This is in place with some caveats on how the form data is stored and styling, separate issues can be raised for outstanding items as far as I'm concerned.

**Comment by kahboom** [comment]
Perfect, closing this out and will create a new one for those minor changes later on. Thanks @gashcrumb .
