### ISSUE TITLE
When connector has no config, unable to view action in integration editor

### ISSUE THREAD

**Issue by kcbabo** [redhat-ipaas/ipaas-ui#420]
After I've set a start/finish connection in the integration editor and selected an action, the UI moves on to other steps.  If I go back to the connection, I can't see which action is used.  I think this might have changed when we decided to skip config page when an action had no config parameters.

**Comment by kcbabo** [comment]
I just need to be able to see which action is used on a connection even if it has no config.

**Comment by gashcrumb** [comment]
Yeah, I mean the only way you'd see the action is via that config page even if it's empty.

Unless we add the action name to the connection name in the side-bar but that's gonna get terrible looking the moment you pick 'Salesforce Example - Create/Update Contact'

Maybe instead of skipping the config page we just show some text like `No configuration is needed for this action` and then keep the page.  @sjcox-rh @dongniwang ?

**Comment by kcbabo** [comment]
Yeah, we need to be a bit creative here.  I think it would be cool if there was a separate header or something on the config page which had the action name.  Config would be below that.  Header would always be present when clicking on a connection.   Config would only be shown if the action has configuration.

**Comment by gashcrumb** [comment]
Okay, so I can break up the `<h1>` tag, so instead of (for example) `Configure HTTP GET` it's just `HTTP GET` and then below that we have the configuration section *or* a note that there's no config necessary.

**Comment by gashcrumb** [comment]
Linked PR makes this happen instead ->
![screencapture-localhost-4200-integrations-create-action-configure-1-1492010603249](https://cloud.githubusercontent.com/assets/351660/24965589/7d147ec0-1f72-11e7-99b6-0856b574755d.png)

**Comment by kcbabo** [comment]
Perfect!

**Comment by kcbabo** [comment]
OK, there's a couple tweaks I'd like to make here.  This change now means I have to click Next again if there's no configuration, which I would prefer not to do.  Also, if I click on a connection to see the action configuration, I have to click next to get out of the view before doing something else in the UI (e.g. adding a step).

Can I have the best of both worlds? :-)

**Comment by gashcrumb** [comment]
We could maybe add the action underneath the connection name in the sidebar
on a second line?  Then it'd be possible to skip that page...

**Comment by gashcrumb** [comment]
I tried just kinda sticking the action name underneath the connection name but it looked kinda busy.  What about using the action name in the integration instead, for example:

![screencapture-localhost-4200-integrations-edit-2-save-or-add-step-1492102210067](https://cloud.githubusercontent.com/assets/351660/25014953/d5530950-2047-11e7-812e-8852582621b5.png)

or maybe a better example:

![screencapture-localhost-4200-integrations-edit-1-save-or-add-step-1492102313700](https://cloud.githubusercontent.com/assets/351660/25015010/0b051552-2048-11e7-8278-639d3f01e18f.png)

**Comment by gashcrumb** [comment]
K, lemme know how that goes, @sjcox-rh might need to ponder this one longer term.

**Comment by kahboom** [comment]
What the hell... the skinny donut is back again?? But how? I just fixed it lol. Guess only for a single step. Will have to take a look at that when I get back later.

**Comment by kahboom** [comment]
@gashcrumb - This was reopened, is it not complete?

**Comment by gashcrumb** [comment]
Yeah, I think we can close this now
