### ISSUE TITLE
Clicking on integration item no longer automatically takes user to edit screen.

### ISSUE THREAD

**Issue by jbakermd** [redhat-ipaas/ipaas-ui#430]
This might be intended behaviour, but if not, fyi: Yesterday I was able to click anywhere on an integration (highlighted in blue in the screenshot below) on the integration list page, and I'd be automatically taken to an edit page for that integration.

Now the only way to get to said edit page is to use the "..." menu on the right (show below):

![screen shot 2017-04-12 at 3 34 49 pm](https://cloud.githubusercontent.com/assets/26657480/24979224/0aec86a4-1f99-11e7-9de5-767a2be9b421.png)

**Comment by kahboom** [comment]
This should be fixed now! Thanks! 👍
