### ISSUE TITLE
Publish button stays active, no progress indicator

### ISSUE THREAD

**Issue by rhuss** [redhat-ipaas/ipaas-ui#435]
When publishing an integration via pushing the "Publish" button, the button remains active and no progress indicator is shown. Which is confusing, as one cannot be sure whether the button has been really pushed (since there is no visible state change).

I would expect:

* To disable the button immediately to avoid double presses
* To show some sort of progress indicator like a spinning wheel

**Comment by gashcrumb** [comment]
Saves are kinda supposed to be fast but I agree the button state should at least go to disabled and have a spinner in any case.
