### ISSUE TITLE
wrong links to icons in Connections > Create connection 

### ISSUE THREAD

**Issue by jludvice** [redhat-ipaas/ipaas-ui#437]
connections list:
![image](https://cloud.githubusercontent.com/assets/8707241/25004856/b3b6bc38-2056-11e7-9c34-c01dc2cdfaa9.png)
connections:create
![image](https://cloud.githubusercontent.com/assets/8707241/25004892/d915140c-2056-11e7-9b76-81b9c3d8c3f0.png)

**Comment by gashcrumb** [comment]
Think we're waiting on day trade/trade insight icons from UXD but the other ones are fixed with that PR
