### ISSUE TITLE
Missing Connector Icons: ServiceNow & Messaging

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#453]
In the Connections List view, the icons for Messaging and ServiceNow are missing. Broken link image is shown instead.

cc @sjcox-rh @dongniwang - I see that we have the Messaging icon, so there must be something wrong with the image icon path that I'll check on now, but I don't see a ServiceNow icon in the repository. Do we have one? Also, please verify that this is the correct Messaging icon:

![messaging connection](https://cloud.githubusercontent.com/assets/3844502/25090554/e2b95de4-2351-11e7-9b0b-f20d5ec1303f.png)

Thanks in advance! :purple_heart:

## Reference
- [JIRA](https://issues.jboss.org/browse/IPAAS-311)

**Comment by kahboom** [comment]
The issue with the Messaging icon is that the connector is actually `jms`. We can filter this in the UI and check `if 'jms' then render the 'messaging' icon` type of thing, but I gather this is not the best practice as they should be consistent. So, we are left with two options:

1. Have the API change the string of text to 'messaging' instead of 'jms'.
2. Provide two separate icons and connectors, one for 'messaging' and another for 'jms'. These seems better to me as we shouldn't assume all 'messaging' is 'jms'; they are not mutually exclusive.

In the case of 2, we'd obviously need a second icon from UXD.

cc'ing @jimmidyson @chirino @rhuss @KurtStam @gashcrumb  and whoever else is interested in discussing this. :)

**Comment by sjcox-rh** [comment]
@kahboom @dongniwang Yup that's the correct messaging icon!  I haven't provided a ServiceNow icon but I can do that, will send that over shortly.

Are there any other icons that are missing? If so let me know. Actually, do we have a comprehensive list of all connectors we plan on using for summit? That way I can just check them off as I provide them :]

Thanks!

**Comment by kahboom** [comment]
@sjcox-rh - Thanks! So, I believe @kcbabo has listed them in [this](https://docs.google.com/a/redhat.com/document/d/1NQHjA_as74AvVQy7JQL8w20SNgMyb0pk9s5y2xHMMpE/edit?usp=sharing) doc, but maybe he can chime and verify.

So, in that case I'll just go with solution 3 until we can decide to go with 1, 2, or a better solution (I believe everyone in Europe is still on holiday until tomorrow).

**Comment by kahboom** [comment]
@sjcox-rh - That also means that we may end up needing a separate icon for JMS, not sure yet though, we'll see what the rest of the team says.

**Comment by sjcox-rh** [comment]
@kahboom I've attached the servicenow icon in the jira story since github doesn't support uploading of svg's :]

https://issues.jboss.org/browse/IPAAS-250

**Comment by kahboom** [comment]
Thanks @sjcox-rh ! I guess I'll close this issue and we can create one to discuss JMS vs Messaging icons post-Summit.
