### ISSUE TITLE
More bits with poor contrast for presentations and videos

### ISSUE THREAD

**Issue by jimmidyson** [redhat-ipaas/ipaas-ui#468]
@kcbabo noticed these in a recent recording.

<img width="1027" alt="ipaas-3scale-demo-take3_mp4_-_google_drive" src="https://cloud.githubusercontent.com/assets/464659/25135828/52a687d6-244b-11e7-98c7-a5755cd49a2c.png">
<img width="1005" alt="ipaas-3scale-demo-take3_mp4_-_google_drive 1" src="https://cloud.githubusercontent.com/assets/464659/25135834/57dbc888-244b-11e7-965c-796ffb59eb91.png">

**Comment by kahboom** [comment]
@gashcrumb Was this resolved completely or just with removing the radio button? Do we still need to adjust the color of the sidebar?

**Comment by gashcrumb** [comment]
Ah, you know we removed the radio control, so yeah, think this can be
closed now, I darkened the border of the popover.

**Comment by kahboom** [comment]
Cool, thanks!
