### ISSUE TITLE
Mapping Line Gradient?

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-ipaas/ipaas-ui#474]
Currently there is a gradient being used on the connector line within the data mapping canvas. Can that be changed to a solid line?

![unnamed-2](https://cloud.githubusercontent.com/assets/16257540/25165790/ed84f0e4-248c-11e7-854b-3d75ca7a2fb5.png)

**Comment by gashcrumb** [comment]
@jbakermd FYI, let me create an issue in datamapper-ui

**Comment by gashcrumb** [comment]
Let's track this issue in the datamapper-ui repo...

**Comment by mattrpav** [comment]
Hi SJ-

Sure thing. Is there a specific color you had in mind or should we match the same blue used in the item highlight?

Thanks,
Matt
