### ISSUE TITLE
Integration List - All are constantly loading

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-ipaas/ipaas-ui#475]
When viewing integration list, all integrations seems to be constantly loading. Not sure if it's a bug but wanted to track it just in case.

![unnamed-3](https://cloud.githubusercontent.com/assets/16257540/25165812/199a9db4-248d-11e7-9c5f-374b09e1286f.png)

**Comment by gashcrumb** [comment]
Yeah, it's a data issue, the `currentStatus` field doesn't ever change to match the `desiredStatus` field.

@KurtStam, maybe in the example integrations we can just have the `currentStatus` = `desiredStatus`?

**Comment by kahboom** [comment]
So, for the most part this looks to be resolved, with the exception of 'Activated' Integrations, which don't return a `currentStatus` property at all. See my PR [here](https://github.com/redhat-ipaas/ipaas-ui/pull/493).

**Comment by gashcrumb** [comment]
Think this one is all set.
