### ISSUE TITLE
Create Connection: progress indicator is one step behind

### ISSUE THREAD

**Issue by dsimansk** [redhat-ipaas/ipaas-ui#510]
The progress indicator should be on `step 3` when requesting Connection details. 

![screen shot 2017-04-24 at 13 24 56](https://cloud.githubusercontent.com/assets/5637792/25335052/8d6cccd6-28f1-11e7-9f44-0a3232d4463e.png)

**Comment by dsimansk** [comment]
I've also noticed that there's `Next` button, where used to be `Create` according to e2e scenario. However, the button itself is disabled (not invoking any further action).

cc @jludvice @kahboom @gashcrumb

**Comment by gashcrumb** [comment]
The 'next' button is disabled on the first page as the flow has changed where you click on a connector and the wizard goes to the next page.  I'll remove that one.  Looking here on the last page I do see a 'Create' button, I do also see that the highlighted step is still on 2.  Seems like you can't go back either, so lemme look into those.

**Comment by gashcrumb** [comment]
Should be set now with that PR, lemme know :-)

**Comment by dsimansk** [comment]
Look all right now, thanks @gashcrumb. Closing the issue now.
