### ISSUE TITLE
automate keycloak first login form

### ISSUE THREAD

**Issue by jludvice** [redhat-ipaas/ipaas-ui#513]
I thought this could be the place to check current url and if it contains some keycloak pattern, 
then invoke `KeycloakLogin.fillForm` (or something like that)
https://github.com/redhat-ipaas/ipaas-ui/blob/3e6d4ef34d502abcca7ef1c101dfea1ab5ad5113/e2e/app.po.ts#L146

**Comment by jludvice** [comment]
It might be tricky to find the right place though.
User is first redirected to github, then eventually to keycloak and then to ipaas ui.

**Comment by dsimansk** [comment]
Closed via #519
