### ISSUE TITLE
Connections: State Management Issue w/ Steps & Workflow

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#91]
Currently experiencing an issue where if you press the 'Back' button when creating a Connection there is an issue with state management. The entire app goes bonkers. I believe the same happens if you cancel out of creating a connection and attempt to creation another one.

**Comment by kahboom** [comment]
Is this still an issue after @jimmidyson 's implementation? Haven't had a chance to test.

**Comment by gashcrumb** [comment]
That wizard hasn't been brought over (yet), so not sure if this is applicable at the moment.  We may want to kinda implement that flow a little differently, but keep these state management gotchas in mind.
