### ISSUE TITLE
Creating Connections: Dynamic Form Validation

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-ui#96]
Right now it's not really truly validating anything. We need to figure out how this will work with the API.

**Comment by jstrachan** [comment]
in angular 1.x we used [hawtio-forms](https://github.com/hawtio/hawtio-forms) to turn JSON Schema into forms that performed completion + validation that were then extensible with custom components or customisation. It'd be nice to have an angular 2 version for lots of use cases. e.g. the Connector's have JSON Schema for all their properties & data types
